[gcp_service_account]
type = "service_account"
project_id = "erudite-wind-461914-t6"
private_key_id = "5c2aeac3273b3fe905a530f59111fe13f24d0199"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC/ij8D0vioOhlT
YNwPkY+k0SPmJ323dF+WVE9066LMvBYYdj800QJEAoYbTbdSksWzJGxBSOif1Lul
lbHgNbKHjF54purnQ2iEIAghGZ6ymtRygpwvAqqG8dB7+N9kOlUdCluEo98ahViS
gPtxJ6M2LkMiPoTTxhCxuT0b9bpWlgLXJU6nuz8MNksJu0uC50NRGQn2BzOmQJqU
pgZrXB/Gij8axXOXc9JKnPL0l8DZf2rD1glnwfRvRtd7W8UrFV6F3xOYQrnUMRtD
ehBvjWQK+owRiryujFk5NC+8fri38r6TXuLuKBFlFwRW/SMLEarXLUiZ4yRHJw8u
DkTcN4EpAgMBAAECggEAD+x174MJJe/fPfcKEdJGY0ukJM9zgb5Z7wUXLk95CJ/P
ZMe52qcl/Xz0j2MJ4q0Yj1uFE3VfVOBU8aptBV3kInrj5LsYbChcEUtExGmymkMf
ITOkuTogbq5o/dF+KEE65Q/rdVlr+XK3XxtRgWyr7TEckYV/OfLtXYpv9I8x0gj/
7k5ErtdhT0n/8BWZhvsrYSMwnGnoPtbzk6gM42SCFM52pzqtXGfotiuXZUs5In8N
q0O9sgOFQAknP0kFwUcbKyBFQGJdQZ+oB1+Md+VZ+vh7dqC3bgpaXiDSxyn21XDl
WgGZY7EgTOl2rNe8u1bw4s0hOhzFdhkiSBhQDc39jQKBgQD/whDFoMI5N+/EsFLc
CtUJzTN1dpiF/Kt71aWxffzVMEiEofMLNgTRS62LrZWXQwioBkhXdiFbzv3EiVMN
4FCUFQ63XVkT1FS6ku5n1SSNlor2mJwwrhXUfq72neJIJ1k1CXcqpvMH9tbrmJXY
OROuD/s8J6AxlZXI6Bz66D8DBQKBgQC/uKErT+puLm1lKU3cCdYezAltOGh0/E3X
l5/3CzaaQ7k4TbJU4KDGuLM+D24VydecZYV5clzzgKIRbtsOKcN5SeSG6OWZ3Kgc
Nrr5JtgHQx8slBnWhX+sX7/40NRwf7KMK6xBhtBckSEL5fNJsGKQ+ANq34cgFp5Q
nnHSJoh5m1QKBgAj7yhcHBIt5+YQRJXfxMXZ8rLgNiGH8dBGPeZh4cm8SmRl/jsfw
B89KNzhWypBbnGw6fEQGNDnDVYqXwEEWhf4Nl0y9jKlzpd4/1vvysqv+g7cRuTrE
gqPKJ18mQJKEP0/rmzH2V0cKVpZD789+gcB1cz+zrJ7RQEekT5BIpB35AoGAQGEI
RdoNF7ihZYHsMkJfU3IijDmP4hDDNu0kezmZuU2aicyVYKkZdAGbtvBJgCmKLGtu
2axMiDwesAnwpx3hFP56Lc9RIkyVavv55yZjDnU8p6SH1KB5kfGJLk05uRk4ZJdZ
vZs+pobZePxbqNgBETsnMqEi5+SQfvM6sujsmo0CgYEAy0Vt/Whc2SddDMSaxOhz
dxI3UGNOUohBktk1+swuAEySqF+6SskQ5hXQ7w61Ej7EMqoNP5M4HwQ6nbJGY9BD
LTTOiR8G7pC4zRYUr0ydiNR/rVWjpeYEtpXInOVK4DbZyIjd5ZTpDM/XvH0buqxj
2i0eh8E0n2QupVT96NNRlwI=
-----END PRIVATE KEY-----"""
client_email = "streamlit-rh-service-account@erudite-wind-461914-t6.iam.gserviceaccount.com"
client_id = "102270462288721571110"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-rh-service-account%40erudite-wind-461914-t6.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

spreadsheet_id = "1TgV3CJTWL9dlNHMbD1Zq467ffUkgtqOURyRGuBQ_N3g"
worksheet_name = "RegistosHoras"